### PR TITLE
adds section on modern HOL4 surface syntax

### PR DESCRIPTION
**Pull request by arolle**
and fix compilation errors

### CODE REVIEW

**Comment by mn200** [comment]
One aspect of the "modern" HOL syntax that you have not covered is the way rules in {Co,}Inductive definitions can be labeled with square-bracket syntax.  E.g.,
```
Inductive foo:
[~rule1:]
blah-blah ==> foo x y /\
[~rule2:]
foo c1 x
End
```

**Comment by arolle** [comment]
The most-recent commit introduces the rule labels.

**Comment by mn200** [comment]
Awesome; thanks!

**Comment by arolle** [comment]
Could you deploy the changes to [the online version of the guidebook](https://hol-theorem-prover.org/guidebook/)?

**Comment by mn200** [comment]
I think this may require @xrchz (?)

**Comment by arolle** [comment]
There is a `publish` target in the [`Holmakefile`](https://github.com/HOL-Theorem-Prover/hol-guidebook/blob/a0247e9a897b6859a537d6b40c96dffdb8289a2f/Holmakefile#L7C1-L7C8) which probably does the job.

**Comment by mn200** [comment]
Only if you have credentials to `rsync` to the server...

**Pull request merged**
